apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "flyteagent.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteagent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "flyteagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{ include "flyteagent.podLabels" . | nindent 8 }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - command:
        - pyflyte
        - serve
        - agent
        {{- if .Values.podEnv }}
        env:
        {{- with .Values.podEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: flyteagent
        volumeMounts: {{- include "agentSecret.volumeMount" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
          name: {{ .Values.ports.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.additionalVolumeMounts -}}
        {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.additionalContainers -}}
      {{- tpl (toYaml .) $ | nindent 6}}
      {{- end }}
      serviceAccountName: {{ template "flyteagent.name" . }}
      volumes: {{- include "agentSecret.volume" . | nindent 6 }}
      {{- with .Values.additionalVolumes -}}
      {{ tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
