storage:
  type: stow
  stow:
    kind: s3
    config:
      auth_type: iam
      region: us-east-2
  # TODO replace with the container (bucket) in s3 used by Flyte as intermediate store
  container: "flyte-demo"
  # NOTE this cache configuration is purely for propeller. But since we are having a common storage
  # config, we are configuring this value. In production create a separate storage config for
  # propeller and increase the cache size
  cache:
    max_size_mbs: 512
    target_gc_percent: 70
  limits:
    maxDownloadMBs: 10
