apiVersion: v2
name: flyte-sandbox
description: A Helm chart for the Flyte local sandbox

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.1"

dependencies:
  - name: docker-registry
    version: 2.2.2
    repository: https://twuni.github.io/docker-registry.helm
    condition: docker-registry.enabled
  - name: flyte-binary
    version: v0.1.10
    repository: file://../flyte-binary
    condition: flyte-binary.enabled
  - name: kubernetes-dashboard
    version: 6.0.0
    repository: https://kubernetes-retired.github.io/dashboard/
    condition: kubernetes-dashboard.enabled
  - name: minio
    version: 12.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: postgresql
    version: 12.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
