apiVersion: v1
kind: Service
metadata:
  name: flyteadmin
  namespace: flyte
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ports:
  - name: redoc
    protocol: TCP
    port: 87
    targetPort: 8087
  - name: http-metrics
    protocol: TCP
    port: 10254
