# This is a sample configuration file.
# Real configuration when running inside K8s (local or otherwise) lives in a ConfigMap
# Look in the artifacts directory in the flyte repo for what's actually run
logger:
  level: 5
application:
  grpcPort: 8081
  httpPort: 8080
  grpcServerReflection: true
datacatalog:
  storage-prefix: "metadata"
  metrics-scope: "datacatalog"
  profiler-port: 10254
storage:
  connection:
    access-key: minio
    auth-type: accesskey
    disable-ssl: true
    endpoint: http://localhost:9000
    region: my-region-here
    secret-key: miniostorage
  cache:
    max_size_mbs: 10
    target_gc_percent: 100
  container: my-container
  type: minio
database:
  port: 5432
  username: postgres
  host: localhost
  dbname: datacatalog
  options: "sslmode=disable"
