# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Selvatico/go-mocket"
  version = "1.0.7"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.11"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"

[[override]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/lyft/flyteidl"
  source = "https://github.com/lyft/flyteidl"
  version = "^0.16.x"

[[override]]
  name = "github.com/lyft/flytestdlib"
  source = "https://github.com/lyft/flytestdlib"
  version = "^v0.2.24"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.25.1"

[prune]
  go-tests = true
  unused-packages = true
