{{- if .Values.datacatalog.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "datacatalog.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "datacatalog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.datacatalog.replicaCount }}
  selector:
    matchLabels: {{ include "datacatalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/datacatalog/configmap.yaml") . | sha256sum | trunc 63 | quote }}
        {{- with .Values.datacatalog.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{ include "datacatalog.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
      {{- if .Values.db.checks }}
      - name: check-db-ready
        image: postgres:10.16-alpine
        securityContext:
          runAsUser: 0
        command:
          - sh
          - -c
          - until pg_isready -h {{ tpl .Values.db.datacatalog.database.host $ }} -p {{ .Values.db.datacatalog.database.port }}; do echo waiting for database; sleep 2; done;
      {{- end }}
      - command:
        - datacatalog
        - --config
        - {{ .Values.datacatalog.configPath }}
        - migrate
        - run
        image: "{{ .Values.datacatalog.image.repository }}:{{ .Values.datacatalog.image.tag }}"
        imagePullPolicy: "{{ .Values.datacatalog.image.pullPolicy }}"
        name: run-migrations
        volumeMounts: {{- include "databaseSecret.volumeMount" . | nindent 8 }}
        - mountPath: /etc/datacatalog/config
          name: config-volume
      containers:
      - command:
        - datacatalog
        - --config
        - {{ .Values.datacatalog.configPath }}
        {{- with .Values.datacatalog.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - serve
        image: "{{ .Values.datacatalog.image.repository }}:{{ .Values.datacatalog.image.tag }}"
        imagePullPolicy: "{{ .Values.datacatalog.image.pullPolicy }}"
        name: datacatalog
        ports:
        - containerPort: 8088
        - containerPort: 8089
        - containerPort: {{ index .Values.configmap.datacatalogServer.datacatalog "profiler-port" }}
        resources: {{ toYaml .Values.datacatalog.resources | nindent 10 }}
        volumeMounts: {{- include "databaseSecret.volumeMount" . | nindent 8 }}
        - mountPath: /etc/datacatalog/config
          name: config-volume
      serviceAccountName: {{ template "datacatalog.name" . }}
      volumes: {{- include "databaseSecret.volume" . | nindent 6 }}
      - emptyDir: {}
        name: shared-data
      - configMap:
          name: datacatalog-config
        name: config-volume
      {{- with .Values.datacatalog.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.datacatalog.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.datacatalog.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}
