{{- if .Values.datacatalog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "datacatalog.name" . }}
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "datacatalog.labels" . | nindent 4 }}
  {{- with .Values.datacatalog.service.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.datacatalog.service.type}}
  type: {{ . }}
  {{- end }}
  ports:
  - name: grpc-2
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: http
    port: 88
    protocol: TCP
    targetPort: 8088
  - name: grpc
    port: 89
    protocol: TCP
    targetPort: 8089
  selector: {{ include "datacatalog.selectorLabels" . | nindent 4 }}
{{- end }}
