# Service
apiVersion: v1
kind: Service
metadata:
  name: cacheservice 
  namespace: flyte
  annotations:
    # This tells contour to use a H2 connection for the port associated
    # with the name 'grpc' under spec/ports.
    # For more information, refer to
    # https://github.com/heptio/contour/blob/master/docs/annotations.md#contour-specific-service-annotations
    contour.heptio.com/upstream-protocol.h2c: "grpc"
spec:
  selector:
    app: cacheservice 
  ports:
  - name: http
    protocol: TCP
    port: 88
    targetPort: 8088
  - name: grpc
    protocol: TCP
    port: 89
    targetPort: 8089
