{{- if and ( not ( index .Values "flyte-binary" "enabled" ) ) .Values.sandbox.dev }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "flyte-sandbox.localHeadlessService" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-sandbox.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: '%{HOST_GATEWAY_IP}%'
    ports:
      - name: http
        port: 8088
        protocol: TCP
      - name: grpc
        port: 8089
        protocol: TCP
      - name: webhook
        port: 9443
        protocol: TCP
      - name: artifact-http
        port: 50050
        protocol: TCP
      - name: artifact-grpc
        port: 50051
        protocol: TCP
{{- end }}
