{{- if and ( not ( index .Values "flyte-binary" "enabled" ) ) .Values.sandbox.dev }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flyte-sandbox.localHeadlessService" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8088
      protocol: TCP
    - name: grpc
      port: 8089
      protocol: TCP
    - name: webhook
      port: 9443
      protocol: TCP
    - name: user
      port: 15605
      protocol: TCP
{{- end }}
