apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # All the resources that make up the deployment
  - flyte
  ########
  # Operators to be enabled
  #############
  # Dependencies to be configured
  # In local we use minio, but in cloud environment use S3 / GCS / AFS / Oracle Blob store etc
  # This is used for Resource pooling. On cloud you can use hosted redis (e.g. AWS elasticache)
  # Contour is used to create ingress. On cloud service use the default provided ingress controllers or cloud LB's
  # Add node ports for ease of use locally
  - ../../base/ingress
  - ../../base/operators/spark
  - ../../base/operators/kfoperators/pytorch
  - ../../base/addons/cloudsqlproxy
  # Optional dependency
  - ../../base/addons/redis

# Images that should be used
images:
  # FlyteAdmin
  - name: flyteadmin # match images with this name
    newTag: v1.10.7-b2 # FLYTEADMIN_TAG override the tag
    newName: cr.flyte.org/flyteorg/flyteadmin # override the name
  # FlyteConsole
  - name: flyteconsole # match images with this name
    newTag: v1.10.2 # FLYTECONSOLE_TAG  the tag
    newName: cr.flyte.org/flyteorg/flyteconsole # override the namep
  # Flyte DataCatalog
  - name: datacatalog # match images with this name
    newTag: v1.10.7-b2 # DATACATALOG_TAG override the tag
    newName: cr.flyte.org/flyteorg/datacatalog # override the name
  # FlytePropeller
  - name: flytepropeller # match images with this name
    newTag: v1.10.7-b2 # FLYTEPROPELLER_TAG override the tag
    newName: cr.flyte.org/flyteorg/flytepropeller # override the name
  # Webhook
  - name: webhook # match images with this name
    newTag: v1.10.7-b2 # FLYTEPROPELLER_TAG override the tag
    newName: cr.flyte.org/flyteorg/flytepropeller # override the name
  # Override postgres image to use alpine based (rather smaller) docker image
  - name: postgres
    newTag: 13-21.04_beta
    newName: ecr.flyte.org/ubuntu/postgres
  - name: minio
    newTag: 2021.10.13-debian-10-r0
    newName: ecr.flyte.org/bitnami/minio
  - name: redis
    newTag: 6.2.5-debian-10-r59
    newName: ecr.flyte.org/bitnami/redis
