apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override the namespace
namespace: flyte

bases:
- ../../base/single_cluster/complete

# All the resources that make up the deployment
- datacatalog/service.yaml
- propeller/service.yaml
  ########
  # Operators to be enabled
  #############
  # Dependencies to be configured
  # In local we use minio, but in cloud environment use S3 / GCS / AFS / Oracle Blob store etc
  # This is used for Resource pooling. On cloud you can use hosted redis (e.g. AWS elasticache)
  # Contour is used to create ingress. On cloud service use the default provided ingress controllers or cloud LB's
  # Add node ports for ease of use locally
resources:
- ../../base/operators/spark
- ../../base/operators/kfoperators/pytorch
- ./dependencies/cloudsqlproxy
  # Optional dependency
- ./dependencies/redis

patchesStrategicMerge:
- admin/deployment.yaml
- admin/service.yaml
- datacatalog/deployment.yaml
- propeller/deployment.yaml
- console/service.yaml

# Files are read in alphabetical order. To ensure that we create the namespace first, prefix the file name with "aa".

configMapGenerator:
- behavior: merge
  files:
  - ./config/admin/db.yaml
  - ./config/admin/remote_data.yaml
  - ./config/admin/task_resource_defaults.yaml
  - ./config/common/storage.yaml
  name: flyte-admin-config
- behavior: merge
  files:
  - ./config/clusterresource-templates/ac_project-copilot-dataconfig.yaml
  - ./config/clusterresource-templates/ad_spark-role.yaml
  - ./config/clusterresource-templates/ae_spark-service-account.yaml
  - ./config/clusterresource-templates/af_spark-role-binding.yaml
  name: clusterresource-template
- behavior: merge
  files:
  - ./config/propeller/core.yaml
  - ./config/propeller/enabled_plugins.yaml
  - ./config/propeller/plugins/catalog_cache.yaml
  - ./config/propeller/plugins/k8s.yaml
  - ./config/propeller/plugins/qubole.yaml
  - ./config/propeller/plugins/spark.yaml
  - ./config/propeller/plugins/task_logs.yaml
  - ./config/common/storage.yaml
  name: flyte-propeller-config
- behavior: merge
  files:
  - ./config/common/storage.yaml
  - ./config/datacatalog/db.yaml
  name: datacatalog-config

###########
# Use this to record the password for the Google CloudSQL Database
secretGenerator:
- name: db-pass
  behavior: merge
  literals:
  - pass.txt="yourpassword"

# Images that should be used
images:
  # FlyteAdmin
  - name: flyteadmin # match images with this name
    newTag: v0.3.15 # override the tag
    newName: docker.io/lyft/flyteadmin # override the name
  # FlyteConsole
  - name: flyteconsole # match images with this name
    newTag: v0.17.7 # override the tag
    newName: docker.io/lyft/flyteconsole # override the namep 
  # Flyte DataCatalog
  - name: datacatalog # match images with this name
    newTag: v0.2.2 # override the tag
    newName: docker.io/lyft/datacatalog # override the name
  # FlytePropeller
  - name: flytepropeller # match images with this name
    newTag: v0.5.2 # override the tag
    newName: docker.io/lyft/flytepropeller # override the name
