apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacatalog
  namespace: flyte
  labels:
    app: datacatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacatalog
  template:
    metadata:
      labels:
        app: datacatalog
        app.kubernetes.io/name: datacatalog
        app.kubernetes.io/version: 0.3.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 1001
        fsGroupChangePolicy: "Always"
      serviceAccountName: datacatalog
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: datacatalog-config
      - name: db-pass
        secret:
          secretName: db-pass
      initContainers:
      - name: run-migrations
        image: datacatalog:v0.3.0
        imagePullPolicy: IfNotPresent
        command: ["datacatalog", "--config", "/etc/datacatalog/config/*.yaml", "migrate", "run"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/datacatalog/config
        - name: db-pass
          mountPath: /etc/db
      containers:
      - name: datacatalog
        image: datacatalog:v0.3.0
        imagePullPolicy: IfNotPresent
        command: ["datacatalog", "--config", "/etc/datacatalog/config/*.yaml", "serve"]
        ports:
        - containerPort: 8088
        - containerPort: 8089
        volumeMounts:
        - name: config-volume
          mountPath: /etc/datacatalog/config
        - name: db-pass
          mountPath: /etc/db
