flyteadmin:
  enabled: false
  serviceAccount:
    # Ensure service account for (controlplane) flyteadmin to connect to (dataplane) flytepropeller exists
    alwaysCreate: true

cluster_resource_manager:
  enabled: false

workflow_scheduler:
  enabled: false

flytescheduler:
  enabled: false

cacheservice:
  enabled: false

datacatalog:
  enabled: false

flyteconsole:
  enabled: false

flyteagent:
  enabled: false
