{{- if not .Values.clusterResourceTemplates.externalConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flyte-binary.clusterResourceTemplates.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.clusterResourceTemplates.labels }}
    {{- tpl ( .Values.clusterResourceTemplates.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.clusterResourceTemplates.annotations }}
    {{- tpl ( .Values.clusterResourceTemplates.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
data:
  {{- if .Values.clusterResourceTemplates.inline }}
  {{- toYaml .Values.clusterResourceTemplates.inline | nindent 2 }}
  {{- else }}
  {{- (.Files.Glob "defaults/cluster-resource-templates/*.yaml").AsConfig | nindent 2 }}
  {{- end }}
{{- end }}
