{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flyte-binary.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-binary.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.labels }}
    {{- tpl ( .Values.serviceAccount.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- tpl ( .Values.serviceAccount.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- tpl ( .Values.serviceAccount.imagePullSecrets | toYaml ) . | nindent 2 }}
{{- end }}
{{- end }}
