# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/envoyproxy/protoc-gen-validate"]

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.5.1"

[[constraint]]
  name = "github.com/lyft/flytestdlib"
  version = "^0.2.x"

[[constraint]]
  name = "github.com/envoyproxy/protoc-gen-validate"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[prune]
  go-tests = true
  unused-packages = true
