{{- if .Values.sandbox.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flyte-sandbox.fullname" . }}-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "flyte-sandbox.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "flyte-sandbox.proxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "flyte-sandbox.proxySelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy
          {{- with .Values.sandbox.proxy.image }}
          image: {{ printf "%s:%s" .repository .tag | quote }}
          imagePullPolicy: {{ .pullPolicy | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
      volumes:
        - name: config
          configMap:
            name: {{ include "flyte-sandbox.proxyConfigMapName" . }}
{{- end }}
