apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-admin-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
data:
{{- with .Values.db }}
  db.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.domain }}
  domain.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.configmap.logger }}
  logger.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.configmap.adminServer }}
  server.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.configmap.remoteData }}
  remoteData.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
{{- with .Values.configmap.task_resource_defaults }}
  task_resource_defaults.yaml: | {{ toYaml . | nindent 4 }}
{{- end }}
{{- if .Values.workflow_notifications.enabled }}
{{- with .Values.workflow_notifications.config }}
  notifications.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.cluster_resource_manager.enabled }}
{{- with .Values.cluster_resource_manager.config }}
  cluster_resources.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.workflow_scheduler.enabled }}
{{- with .Values.workflow_scheduler.config }}
  scheduler.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
