apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: flyteconsole
  namespace: flyte
spec:
  selector:
    app: flyteconsole
  type: LoadBalancer
  ports:
  - name: redoc
    protocol: TCP
    port: 87
    targetPort: 8087
  - name: http-metrics
    protocol: TCP
    port: 10254
