# ---------------------------------------------------------------------
# FLYTE_connector SETTINGS
# ---------------------------------------------------------------------

# nameOverride String to override flyteconnector.name template
nameOverride: ""
# fullnameOverride String to override flyteconnector.fullname template
fullnameOverride: ""
# commonLabels Add labels to all the deployed resources
commonLabels: {}
# commonAnnotations Add annotations to all the deployed resources
commonAnnotations: {}

connectorSecret:
  # -- Specify your Secret (with sensitive data) or pseudo-manifest (without sensitive data).
  secretData:
    data:
      username: User

# -- Replicas count for flyteconnector deployment
replicaCount: 1
image:
  # -- Docker image for flyteconnector deployment
  repository: cr.flyte.org/flyteorg/flyteconnector  # FLYTEconnector_IMAGE
  # -- Docker image tag
  tag: 1.15.3  # FLYTECONNECTOR_TAG
  # -- Docker image pull policy
  pullPolicy: IfNotPresent
ports:
  containerPort: 8000
  name: connector-grpc
# -- Default resources requests and limits for flyteconnector deployment
resources:
  limits:
    cpu: 500m
    ephemeral-storage: 200Mi
    memory: 300Mi
  requests:
    cpu: 500m
    ephemeral-storage: 200Mi
    memory: 200Mi
# -- Default regex string for searching configuration files
configPath: /etc/flyteconnector/config/*.yaml
# -- Service settings for flyteconnector
service:
  annotations:
    projectcontour.io/upstream-protocol.h2c: grpc
  type: ClusterIP
# -- Configuration for service accounts for flyteconnector
serviceAccount:
  # -- Should a service account be created for flyteconnector
  create: true
  # -- Annotations for ServiceAccount attached to flyteconnector pods
  annotations: {}
  # -- ImagePullSecrets to automatically assign to the service account
  imagePullSecrets: []
# -- Security context for pod
podSecurityContext: {}
# -- Readiness probe for flyteconnector. Use readinessProbe: {} if connector doesn't implement grpc-health-checking service.
# -- https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/#trying-the-feature-out
readinessProbe:
  grpc:
    port: 8000
  initialDelaySeconds: 1
  periodSeconds: 3
# -- Security context for container
securityContext:
  allowPrivilegeEscalation: false
# -- Annotations for flyteconnector pods
podAnnotations: {}
# -- Additional flyteconnector pod container environment variables
podEnv: {}
# -- Labels for flyteconnector pods
podLabels: {}
# -- nodeSelector for flyteconnector deployment
nodeSelector: {}
# -- tolerations for flyteconnector deployment
tolerations: []
# -- affinity for flyteconnector deployment
affinity: {}
# -- Appends additional volumes to the deployment spec. May include template values.
additionalVolumes: []
# -- Appends additional volume mounts to the main container's spec. May include template values.
additionalVolumeMounts: []
# -- Appends additional containers to the deployment spec. May include template values.
additionalContainers: []
# -- Appends extra command line arguments to the main command
extraArgs: {}
# -- Sets priorityClassName for datacatalog pod(s).
priorityClassName: ""
