sudo: required
language: go
go:
- '1.11'
jobs:
  include:
  - stage: test
    name: unit tests
    install: make install
    script: make test_unit
  - stage: test
    name: benchmark tests
    install: make install
    script: make test_benchmark
  - stage: test
    install: make install
    name: lint
    script: make lint
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
    secure: xqB2LwI1qbrPUIYXtaOnIoBX5b1h1ydxOvy5Cu1sS/R2t1BfYHFX5oH0/0Z23bfpQBpzEweXA3145xyjg1Q2vJiN2ebPLmMPduWdjp1be/4xWCnkftZuGW7LDEFg3zuREUMKdfDhkb0uQ5gzIte3TvGh/tJwfxwUHVHQEl1aqPYqbRHRqoLJZiuhgIH+17su5mBFfu/62xXMP8zImLUq4WLrmbmMszLWg3IOu+oawpMXuDsjoxkucdFjmo2rsVUNr3QNo7ock7hl1OYHJZvWuRV+HxCaNRNUrbr8GuWYUSNOB51Ml7kLAlSxnmKJMs1fZRxTPlXR/0+XA8zAWahcKvKxRqguoFNVqYEESS/yRoJhLctgwAjx/btSc1a4BXCwIDFXNFVBGyZiVcLnh9PG6WWXI2YRWSbXmoBG3QN8Dtdpz54qoCpCA7IVWijWBHVXiVbyIn9XmTMFCdMXIFZQ7mzzk6K+894taPSRsia305LCJ2/h1df8bLsw5zcXmjXjZpkxM7rK5nJqx6IiaZ94GmeRER3OQxKTxxBuoZvcWcn9+ni+FtA2EzJuMBxbWLh+jinfqqieLkoOPHeBzAN6YyaPuUQje/dT4tjdf95V+wuojfu/TqIk/o7WwMPgfYWP2tlj0R5GwoA3ZocZRXZYRP/gg1Cje6wCQCOiIPsFC5g=
