apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override the namespace
namespace: flyte

bases:
  - ../../../base/single_cluster/complete

resources:
  - propeller/webhook-secret.yaml

patchesStrategicMerge:
  - admin/deployment.yaml
  - propeller/webhook.yaml

configMapGenerator:
  - behavior: merge
    files:
      - ./config/admin/db.yaml
      - ./config/admin/task_resource_defaults.yaml
      - ./config/common/storage.yaml
      - ./config/common/logger.yaml
    name: flyte-admin-config

  - behavior: merge
    files:
      - ./config/propeller/enabled_plugins.yaml
      - ./config/propeller/resource_manager.yaml
      - ./config/propeller/plugins/k8s.yaml
      - ./config/propeller/plugins/task_logs.yaml
      - ./config/common/storage.yaml
      - ./config/common/logger.yaml
    name: flyte-propeller-config

  - behavior: merge
    files:
      - ./config/common/storage.yaml
      - ./config/common/logger.yaml
      - ./config/datacatalog/db.yaml
    name: datacatalog-config
