{{- if .Values.flytepropeller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-propeller-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
data:
{{- with .Values.configmap.admin }}
  admin.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.catalog }}
  catalog.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.catalog_cache }}
  catalog_cache.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.copilot }}
  copilot.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.core }}
  core.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.enabled_plugins }}
  enabled_plugins.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.k8s }}
  k8s.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.logger }}
  logger.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.qubole }}
  qubole.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- with .Values.configmap.resource_manager }}
  resource_manager.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- if .Values.sparkoperator.enabled }}
{{- with .Values.sparkoperator.plugin_config }}
  spark.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.databricks.enabled }}
{{- with .Values.databricks.plugin_config }}
  databricks.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
  storage.yaml: | {{ tpl (include "storage" .) $ | nindent 4 }}
  cache.yaml: |
    storage:
      cache:
        max_size_mbs: {{ .Values.flytepropeller.cacheSizeMbs }}
        target_gc_percent: 70
{{- with .Values.configmap.task_logs }}
  task_logs.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.flyteagent.enabled }}
{{- with .Values.flyteagent.plugin_config }}
  agent_service.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.configmap.plugins_yaml_enabled }}
{{- /* Intentionally not using with .Values.configmap.plugins since
       we want to be able to render empty plugins.yaml */}}
  plugins.yaml: | {{ tpl (toYaml .Values.configmap.plugins) $ | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-config
  namespace: {{ template "flyte.namespace" . }}
  labels: {{ include "flyteadmin.labels" . | nindent 4 }}
data:
{{- with .Values.connector.plugin_config }}
  connector.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
