{{- if .Values.flytepropeller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "flyte.namespace" . }}
  {{- if .Values.flytepropeller.manager }}
  name: {{ template "flytepropeller-manager.name" . }}
  labels: {{ include "flytepropeller-manager.labels" . | nindent 4 }}
  {{- else }}
  name: {{ template "flytepropeller.name" . }}
  labels: {{ include "flytepropeller.labels" . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.flytepropeller.replicaCount }}
  selector:
    {{- if .Values.flytepropeller.manager }}
    matchLabels: {{ include "flytepropeller-manager.selectorLabels" . | nindent 6 }}
    {{- else }}
    matchLabels: {{ include "flytepropeller.selectorLabels" . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/propeller/configmap.yaml") . | sha256sum | trunc 63 | quote }}
        {{- with .Values.flytepropeller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.flytepropeller.manager }}
      labels: {{ include "flytepropeller-manager.labels" . | nindent 8 }}
      {{- else }}
      labels: {{ include "flytepropeller.labels" . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 1001
        fsGroupChangePolicy: "Always"
      containers:
      - command:
        {{- if .Values.flytepropeller.manager }}
        - flytepropeller-manager
        - --manager.pod-template-namespace
        - {{ template "flyte.namespace" . }}
        {{- else }}
        - flytepropeller
        {{- end }}
        - --config
        - {{ .Values.flytepropeller.configPath }}
        {{- with .Values.flytepropeller.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- if .Values.flytepropeller.manager }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        image: "{{ .Values.flytepropeller.image.repository }}:{{ .Values.flytepropeller.image.tag }}"
        imagePullPolicy: "{{ .Values.flytepropeller.image.pullPolicy }}"
        {{- if .Values.flytepropeller.manager }}
        name: flytepropeller-manager
        {{- else }}
        name: flytepropeller
        {{- end }}
        ports:
        - containerPort: {{ index .Values.configmap.core.propeller "prof-port" }}
        resources: {{ toYaml .Values.flytepropeller.resources | nindent 10 }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/flyte/config
          - name: auth
            mountPath: /etc/secrets/
      serviceAccountName: {{ template "flytepropeller.name" . }}
      volumes:
      - configMap:
          name: flyte-propeller-config
        name: config-volume
      - name: auth
        secret:
          secretName: flyte-secret-auth
      {{- with .Values.flytepropeller.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.flytepropeller.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.flytepropeller.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}
