apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # All the resources that make up the deployment
  - flyte
  ########
  # Operators to be enabled
  #############
  # Dependencies to be configured
  # In local we use minio, but in cloud environment use S3 / GCS / AFS / Oracle Blob store etc
  # This is used for Resource pooling. On cloud you can use hosted redis (e.g. AWS elasticache)
  # Contour is used to create ingress. On cloud service use the default provided ingress controllers or cloud LB's
  # Add node ports for ease of use locally
  - ../../base/ingress
  - ../../base/addons/database
  - ../../base/addons/kubernetes_dashboard
  - ../../base/addons/storage
  - ../../base/addons/contour_ingress_controller

resources:
  - nodeport-services.yaml

# Images that should be used
images:
  # FlyteAdmin
  - name: flyteadmin # match images with this name
    newTag: v0.6.10 # FLYTEADMIN_TAG override the tag
    newName: cr.flyte.org/flyteorg/flyteadmin # override the name
  # FlyteConsole
  - name: flyteconsole # match images with this name
    newTag: v0.20.1 # FLYTECONSOLE_TAG  the tag
    newName: cr.flyte.org/flyteorg/flyteconsole # override the namep
  # Flyte DataCatalog
  - name: datacatalog # match images with this name
    newTag: v0.3.5 # DATACATALOG_TAG override the tag
    newName: cr.flyte.org/flyteorg/datacatalog # override the name
  # FlytePropeller
  - name: flytepropeller # match images with this name
    newTag: v0.12.9 # FLYTEPROPELLER_TAG override the tag
    newName: cr.flyte.org/flyteorg/flytepropeller # override the name
  # Webhook
  - name: webhook # match images with this name
    newTag: v0.12.9 # FLYTEPROPELLER_TAG override the tag
    newName: cr.flyte.org/flyteorg/flytepropeller # override the name
  # Override postgres image to use alpine based (rather smaller) docker image
  - name: postgres
    newTag: 10.16-alpine
  - name: minio/minio
    newTag: RELEASE.2021-04-06T23-11-00Z
