apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override the namespace
namespace: flyte

bases:
- ../../../base/single_cluster/complete

resources:
- datacatalog/service.yaml
- propeller/service.yaml

patchesStrategicMerge:
- admin/deployment.yaml
- admin/service.yaml
- datacatalog/deployment.yaml
- propeller/deployment.yaml
- console/service.yaml

# Files are read in alphabetical order. To ensure that we create the namespace first, prefix the file name with "aa".

configMapGenerator:
- behavior: merge
  files:
  - ./config/admin/db.yaml
  - ./config/admin/task_resource_defaults.yaml
  - ./config/common/storage.yaml
  name: flyte-admin-config
- behavior: merge
  files:
  - ./config/clusterresource-templates/ad_spark-role.yaml
  - ./config/clusterresource-templates/ae_spark-service-account.yaml
  - ./config/clusterresource-templates/af_spark-role-binding.yaml
  name: clusterresource-template
- behavior: merge
  files:
  - ./config/propeller/core.yaml
  - ./config/propeller/enabled_plugins.yaml
  - ./config/propeller/plugins/catalog_cache.yaml
  - ./config/propeller/plugins/k8s.yaml
  - ./config/propeller/plugins/qubole.yaml
  - ./config/propeller/plugins/spark.yaml
  - ./config/propeller/plugins/task_logs.yaml
  - ./config/common/storage.yaml
  name: flyte-propeller-config
- behavior: merge
  files:
  - ./config/common/storage.yaml
  - ./config/datacatalog/db.yaml
  name: datacatalog-config

###########
# Use this to record the password for the Google CloudSQL Database
secretGenerator:
- name: db-pass
  behavior: merge
  literals:
  - pass.txt="yourpassword"
