cluster_resources:
  templatePath: "/etc/flyte/clusterresource/templates"
  customData:
    - production:
        - projectQuotaCpu:
            value: "5"
        - projectQuotaMemory:
            value: "4000Mi"
    - staging:
        - projectQuotaCpu:
            value: "2"
        - projectQuotaMemory:
            value: "3000Mi"
    - development:
        - projectQuotaCpu:
            value: "4"
        - projectQuotaMemory:
            value: "3000Mi"
  refreshInterval: 5m
