apiVersion: v1
kind: Service
metadata:
  name: datacatalog-metrics
  namespace: flyte
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  selector:
    app: datacatalog
  type: LoadBalancer
  ports:
  - name: http-metrics
    protocol: TCP
    port: 10254
