apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacatalog
  namespace: flyte
spec:
  template:
    spec:
      containers:
      - name: datacatalog
        resources:
          limits:
            memory: "1Gi"
            cpu: "2"
            ephemeral-storage: "1000Mi"
