{{- if .Values.sparkoperator.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scheduledsparkapplications.sparkoperator.k8s.io
spec:
  group: sparkoperator.k8s.io
  names:
    kind: ScheduledSparkApplication
    listKind: ScheduledSparkApplicationList
    plural: scheduledsparkapplications
    shortNames:
    - scheduledsparkapp
    singular: scheduledsparkapplication
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            concurrencyPolicy:
              enum:
              - Allow
              - Forbid
              - Replace
            failedRunHistoryLimit:
              minimum: 1
              type: integer
            schedule:
              type: string
            successfulRunHistoryLimit:
              minimum: 1
              type: integer
            template:
              properties:
                deps:
                  properties:
                    downloadTimeout:
                      minimum: 1
                      type: integer
                    maxSimultaneousDownloads:
                      minimum: 1
                      type: integer
                driver:
                  properties:
                    cores:
                      exclusiveMinimum: true
                      minimum: 0
                      type: number
                    podName:
                      pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                executor:
                  properties:
                    cores:
                      exclusiveMinimum: true
                      minimum: 0
                      type: number
                    instances:
                      minimum: 1
                      type: integer
                mode:
                  enum:
                  - cluster
                  - client
                monitoring:
                  properties:
                    prometheus:
                      properties:
                        port:
                          maximum: 49151
                          minimum: 1024
                          type: integer
                pythonVersion:
                  enum:
                  - "2"
                  - "3"
                restartPolicy:
                  properties:
                    onFailureRetries:
                      minimum: 0
                      type: integer
                    onFailureRetryInterval:
                      minimum: 1
                      type: integer
                    onSubmissionFailureRetries:
                      minimum: 0
                      type: integer
                    onSubmissionFailureRetryInterval:
                      minimum: 1
                      type: integer
                    type:
                      enum:
                      - Never
                      - OnFailure
                      - Always
                type:
                  enum:
                  - Java
                  - Scala
                  - Python
                  - R
  version: v1beta1
{{- end }}
