{{- if .Values.sparkoperator.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sparkapplications.sparkoperator.k8s.io
spec:
  group: sparkoperator.k8s.io
  names:
    kind: SparkApplication
    listKind: SparkApplicationList
    plural: sparkapplications
    shortNames:
    - sparkapp
    singular: sparkapplication
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              maxLength: 63
              minLength: 1
              type: string
        spec:
          properties:
            arguments:
              items:
                type: string
              type: array
            deps:
              properties:
                downloadTimeout:
                  minimum: 1
                  type: integer
                maxSimultaneousDownloads:
                  minimum: 1
                  type: integer
            driver:
              properties:
                cores:
                  exclusiveMinimum: true
                  minimum: 0
                  type: number
                podName:
                  pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
            executor:
              properties:
                cores:
                  exclusiveMinimum: true
                  minimum: 0
                  type: number
                instances:
                  minimum: 1
                  type: integer
            failureRetries:
              type: integer
            hadoopConf:
              type: object
            hadoopConfigMap:
              type: string
            image:
              type: string
            imagePullPolicy:
              enum:
              - Always
              - Never
              - IfNotPresent
            imagePullSecrets:
              items:
                type: string
              type: array
            initContainerImage:
              type: string
            mainApplicationFile:
              type: string
            mainClass:
              type: string
            memoryOverheadFactor:
              type: string
            mode:
              enum:
              - cluster
              - client
            monitoring:
              properties:
                exposeDriverMetrics:
                  type: boolean
                exposeExecutorMetrics:
                  type: boolean
                metricsProperties:
                  type: string
                prometheus:
                  properties:
                    port:
                      maximum: 49151
                      minimum: 1024
                      type: integer
            nodeSelector:
              type: object
            pythonVersion:
              enum:
              - "2"
              - "3"
            restartPolicy:
              properties:
                onFailureRetries:
                  minimum: 0
                  type: integer
                onFailureRetryInterval:
                  minimum: 1
                  type: integer
                onSubmissionFailureRetries:
                  minimum: 0
                  type: integer
                onSubmissionFailureRetryInterval:
                  minimum: 1
                  type: integer
                type:
                  enum:
                  - Never
                  - OnFailure
                  - Always
            retryInterval:
              type: integer
            sparkConf:
              type: object
            sparkConfigMap:
              type: string
            sparkVersion:
              type: string
            type:
              enum:
              - Java
              - Scala
              - Python
              - R
            volumes:
              items:
                properties:
                  name:
                    type: string
                type: object
              type: array
          required:
          - type
          - sparkVersion
  version: v1beta1
{{- end }}
