name: Contributors

on:
  schedule:
    - cron: '0 12 * * 1' # At 12 noon on Monday.

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Contributors Action
        uses: hyperledger-tooling/github-contributors-action@main
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.FLYTE_BOT_PAT }}"
          SOURCE_GITHUB_REPOSITORY: flyteorg
          CONTRIBUTORS_SECTION_PATTERN: <!-- CONTRIBUTORS START -->
          CONTRIBUTORS_SECTION_END_PATTERN: <!-- CONTRIBUTORS END -->
          INPUT_TEMPLATE_FILE: ./assets/contributor-template.md
          FILE_WITH_PATTERN: ./README.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: '[auto-update-contributors] update all-contributors'
          committer: Flyte Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: auto-update-contributors
          base: master
          delete-branch: true
          title: 'auto-update contributors'
          labels: auto-update-contributors
          team-reviewers: |
            owners
            maintainers
          draft: false
