on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: false
    secrets:
      AWS_ACCOUNT_ID:
        required: false
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  destroy-cluster:
    name: Destroy Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download-flyte-yaml
        with:
          name: opta-flyte
          path: /home/runner/work/flyte/flyte/opta/cloud
      - uses: actions/download-artifact@v3
        id: download-env-yaml
        with:
          name: opta-env
          path: /home/runner/work/flyte/flyte/opta/cloud
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # This aws account should have admin permissions ...?
          #role-to-assume: "arn:aws:iam::896381257720:role/GitHubAdmin"
          #role-session-name: DestroySession
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
      - name: SETUP AND DESTROY OPTA
        shell: bash
        run: |
          sudo chmod +x /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh
          /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh setup_opta
      - name: DESTROY FLYTE Opta
        shell: bash
        run: |
          cd /home/runner/work/flyte/flyte/opta/cloud/
          opta destroy -c flyte.yaml --auto-approve
      - name: DESTROY OPTA ENV
        shell: bash
        run: |
          cd /home/runner/work/flyte/flyte/opta/cloud/
          opta destroy -c env.yaml --auto-approve
