name: Generate Flyte manifest

on: 
  workflow_dispatch:

jobs:
  update-flyte-releases:
    name: Update Flyte components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Build kustomize
        run: |
          make release_automation
          make kustomize
          make helm
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update Flyte Components
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-releases
          delete-branch: true
          title: 'Update Flyte components'
          body: |
            Updated flyte deployment
            - Updated GCP Flyte kustomize generated manifest file
            - Updated EKS Flyte kustomize generated manifest file
            - Updated Sandbox Flyte  kustomize generated manifest file
            - Updated TEST Flyte kustomize generated manifest file
            - Updated GCP Flyte helm generated manifest file
            - Updated EKS Flyte helm generated manifest file
            - Updated Sandbox Flyte helm generated manifest file
            - Updated TEST Flyte helm generated manifest file
            - Auto-generated by [flyte-bot]
          labels: |
            kustomize
            helm
          team-reviewers: |
            owners
            maintainers
          draft: false