name: Build & Push Docker Images

on:
  pull_request:
    paths-ignore:
      - 'cookbook/docs/**'
      - 'cookbook/deployment/**'
  create:
    tags:
      - v*

jobs:
  push-github:
    name: Push to GHCR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    strategy:
      matrix:
        directory:
          - name: core
            path: .
          - name: pod
            path: integrations/kubernetes
          - name: k8s_spark
            path: integrations/kubernetes
          - name: kfpytorch
            path: integrations/kubernetes
          - name: sagemaker_training
            path: integrations/aws
          - name: sagemaker_pytorch
            path: integrations/aws
          - name: pima_diabetes
            path: case_studies/ml_training
          - name: papermilltasks
            path: integrations/flytekit_plugins
          - name: pandera_examples
            path: integrations/flytekit_plugins
          - name: greatexpectations
            path: integrations/flytekit_plugins
          - name: house_price_prediction
            path: case_studies/ml_training
          - name: mnist_classifier
            path: case_studies/ml_training
          - name: eda
            path: case_studies/feature_engineering
          - name: feast_integration
            path: case_studies/feature_engineering
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build & Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          # https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: ${{ matrix.directory.name }}-latest,${{ matrix.directory.name }}-${{ github.sha }},${{ matrix.directory.name }}-${{ github.event.ref }}
          push_git_tag: ${{ github.event_name != 'pull_request' }}
          push_image_and_stages: ${{ github.event_name != 'pull_request' }}
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:${{ matrix.directory.name }}-${{ github.sha }}"
          context: ./cookbook/${{ matrix.directory.path }}
          dockerfile: ${{ matrix.directory.name }}/Dockerfile
