name: Package & Push Flyte Helm Charts

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master
      - rc/*
  workflow_dispatch:

jobs:
  publish-development-helm-chart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ["flyte-binary", "flyte-core", "flyteagent"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
      - name: Build helm chart
        working-directory: charts
        run: |
          helm dep update ${{ matrix.chart }}
          helm package \
            --app-version=${{ github.sha }} \
            --version=0.0-${{ github.sha }} \
            ${{ matrix.chart }}
          
          if ! ls ${{ matrix.chart }}-* 2>&1 >/dev/null;
          then
              echo "Chart package not found."
              exit 1
          fi
      - name: Publish Helm chart to GHCR
        working-directory: charts
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run:
          helm push ${{ matrix.chart }}-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
