name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      component:
        description: "Component Name"
        required: true
        type: string
      dockerfile:
        description: "Dockerfile name"
        required: true
        type: string
      version:
        description: "Version of image"
        required: true
        type: string
      push:
        description: "Push to registry"
        required: true
        type: boolean
      before-build:
        description: "Script to run before build"
        required: false
        type: string
    secrets:
      FLYTE_BOT_USERNAME:
        required: true
      FLYTE_BOT_PAT:
        required: true
jobs:
  push-github:
    name: Push to Github Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
      - name: Prepare Image Tags
        id: tags
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ inputs.version }}
            type=sha,format=long,prefix=
      - name: Before Build
        run: ${{ inputs.before-build }}
      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/arm64,linux/amd64
          push: ${{ inputs.push }}
          tags: ${{ steps.tags.outputs.tags }}
