name: Pull Request

on: pull_request

jobs:
  tests-lint:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Unit Tests
        run: make mod_download && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Bench tests
        run: make install && make test_benchmark
  lint:
    name: Lint
    uses: flyteorg/flytetools/.github/workflows/lint.yml@master
    with:
      go-version: '1.18'
  test-generate-integrity:
    name: Ensure go generate has run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Go generate and diff
        run: DELTA_CHECK=true make generate

