name: Upgrade Automation
on:
  workflow_dispatch:
    inputs:
      component:
        description: "Name of Flyte component"
        required: true
        default: "boilerplate"
        type: choice
        options:
          - boilerplate
          - flyteidl
jobs:
  trigger-upgrade:
    name: ${{ github.event.inputs.component }} Upgrade
    if: ${{ github.event.inputs.component  == "boilerplate" }}
    uses: flyteorg/flytetools/.github/workflows/flyte_automation.yml@master
    with:
      component: ${{ github.event.inputs.component }}
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  upgrade_flyteidl:
    name: Upgrade Flyteidl
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.component  == "boilerplate" }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Update release
        run: |
          FLYTEIDL_VERSION=$(curl --silent "https://api.github.com/repos/flyteorg/flyteidl/releases/latest" | jq -r .tag_name)
          yarn upgrade @flyteorg/flyteidl@$FLYTEIDL_VERSION
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update Flyteidl version
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-flyteidl
          delete-branch: true
          title: 'Update Flyteidl version'
          body: |
            Update Flyteidl version
            - Auto-generated by [flyte-bot]
          labels: |
            flyteidl
          team-reviewers: |
            owners
            maintainers
          draft: false
